INSERT INTO pays VALUES
(1, 'Jamaïque'),
(2, 'Etats-Unis'),
(3, 'Canada'),
(4, 'Suisse'),
(5, 'Danemark'),
(6, 'France'),
(7, 'Espagne'),
(8, 'Inde'),
(9, 'Japon'),
(10, 'Italie'),
(11, 'Hongrie'),
(12, 'Fédération de Russie'),
(13, 'Chine'),
(14, 'Serbie'),
(15, 'Afrique du Sud'),
(16, 'Grenade'),
(17, 'Kenya'),
(18, 'Grande-Bretagne'),
(19, 'Allemagne');
