INSERT INTO sport VALUES
(1, 'Athletisme - 100m hommes'),
(2, 'Athletisme - 100m femmes'),
(3, 'Aviron - poids légers (4-) hommes'),
(4, 'Badminton - simple femmes'),
(5, 'Basketball - hommes'),
(6, 'Escrime - épée par équipes hommes'),
(7, 'Gymnastique - Multiple individuel femmes'),
(8, 'Gymnastique - Multiple par equipes femmes'),
(9, 'Athletisme - 200m hommes'),
(10, 'Athletisme - 400m hommes'),
(11, 'Handball - femmes'),
(12, 'Natation - 200m Papillon hommes'),
(13, 'Natation - 100m Papillon hommes'),
(14, 'Natation - 200m 4 nages hommes'),
(15, 'Natation - 4x200m nage libre hommes'),
(16, 'Natation - 4x100m 4 nages hommes'),
(17, 'Natation - 4x100m nage libre hommes'),
(18, 'Marathon'),
(19, 'Natation - 200m nage libre hommes');
